### ISSUE TITLE
Can't find annotation because of trailing spaces

### ISSUE THREAD

**Issue by jantimon** [morishitter/css-annotation#1]
```
/*
 * @foo   
 */
```

Does not return `{foo:true}` if there are trailing spaces behind foo.

**Comment by msaktype** [comment]
@jantimon You must write annotations with `@` in front of `foo`.

```
/*
 * @foo
 */
```

Return `{foo: true}`.

**Comment by jantimon** [comment]
Sorry was a typo - the important part is the space after `@foo`.
Please try it again it won't return `{foo: true}`
