### ISSUE TITLE
Feature request - Multiple annotations with the same name

### ISSUE THREAD

**Issue by jantimon** [morishitter/css-annotation#4]
It would be cool if the css-annotion parser would allow to parse multiple annotations with the same name

``` css
/*
 * @file demo1.less
 * @file demo2.less
 *
 */
```

Current result: `{file: demo2.less}`
Expected result: `{file: ['demo1.less','demo1.less']}`

If this sounds reasonable to you I would prepare a pull request

**Comment by msaktype** [comment]
fmm... OK, it is cool :)

We parse the following code:

```
/*
 * @foo
 * @bar bar
 * @foo foo
 */
```

I expect we will get `{foo: ['foo'], bar: 'bar'}`. Not `{foo: [true, 'foo'], bar: 'bar'}`

**Comment by jantimon** [comment]
I absolutely agree.

What would be the desired outcome for the following code?

``` css
/*
 * @foo foo1
 * @foo foo2
 * @bar bar
 * @foo
 */
```

`{ foo: ['foo1', 'foo2'], bar: 'bar' }` ?

**Comment by msaktype** [comment]
Yes, I think so.
